### ISSUE TITLE
Server crash presumably HuskSync

### ISSUE THREAD

**Issue by HarvelsX** [WiIIiam278/HuskSync#15] opened 2022-01-13 00:34 UTC
Build: https://github.com/HarvelsX/HuskSync/tree/reformat (HuskSync 1.2.2)
Core: git-Paper-134 (MC: 1.18.1)
Crashlog:
```bash
[08:43:29] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-134 (MC: 1.18.1) ---
[08:43:30] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[08:43:30] [Paper Watchdog Thread/ERROR]: ------------------------------
[08:43:30] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[08:43:30] [User Authenticator #359/INFO]: UUID of player MrOPimentoO is bcb51f0c-9383-3a45-a7b9-2527fdc8f1e9
[08:43:30] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:item, entity class: net.minecraft.world.entity.item.EntityItem
[08:43:30] [Paper Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[08:43:30] [Paper Watchdog Thread/ERROR]: Entity UUID: c22a5b75-d971-4f87-a523-ee69f46cfa29
[08:43:30] [Paper Watchdog Thread/ERROR]: Position: world: 'world' at location (-849.166259765625, 62.418212890625, -2435.390625)
[08:43:30] [Server thread/INFO]: beviantsev lost connection: Disconnected
[08:43:30] [Paper Watchdog Thread/ERROR]: Velocity: (1.0569685396498082E-115, 0.004318609101522449, -3.349710590944361E-116) (in blocks per tick)
[08:43:30] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[-849.291259765625, 62.4228515625, -2435.515625] -> [-849.041259765625, 62.6728515625, -2435.265625]
[08:43:30] [Paper Watchdog Thread/ERROR]: ------------------------------
[08:43:30] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[08:43:30] [Paper Watchdog Thread/ERROR]: 	PID: 38 | Suspended: false | Native: false | State: RUNNABLE
[08:43:30] [Paper Watchdog Thread/ERROR]: 	Stack:
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream$HandleTable.lookup(ObjectOutputStream.java:2315)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1129)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.HashMap.internalWriteEntries(HashMap.java:1943)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.HashMap.writeObject(HashMap.java:1497)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/jdk.internal.reflect.GeneratedMethodAccessor1107.invoke(Unknown Source)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1201)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1526)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.HashMap.internalWriteEntries(HashMap.java:1944)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.HashMap.writeObject(HashMap.java:1497)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/jdk.internal.reflect.GeneratedMethodAccessor1107.invoke(Unknown Source)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1201)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1526)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeRecordData(ObjectOutputStream.java:1500)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		HuskSync.jar//me.william278.husksync.redis.RedisMessage.serialize(RedisMessage.java:180)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		HuskSync.jar//me.william278.husksync.bukkit.data.DataSerializer.getSerializedStatisticData(DataSerializer.java:294)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		HuskSync.jar//me.william278.husksync.bukkit.util.PlayerSetter.getNewSerializedPlayerData(PlayerSetter.java:54)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		HuskSync.jar//me.william278.husksync.bukkit.util.PlayerSetter.updatePlayerData(PlayerSetter.java:103)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		HuskSync.jar//me.william278.husksync.bukkit.listener.BukkitEventListener.onPlayerQuit(BukkitEventListener.java:39)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor$$Lambda$5529/0x0000000801b923d0.execute(Unknown Source)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.players.PlayerList.remove(PlayerList.java:606)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.players.PlayerList.remove(PlayerList.java:591)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1990)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1970)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.Connection.handleDisconnection(Connection.java:714)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$3995/0x000000080143c740.run(Unknown Source)
[08:43:30] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
[08:43:30] [Paper Watchdog Thread/ERROR]: ------------------------------
[08:43:30] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[08:43:30] [Paper Watchdog Thread/ERROR]: ------------------------------
```

**Comment by WiIIiam278** [comment] 2022-01-13 00:38
I've not received any reports of this crash from anyone and I reckon I would've by now if it were on the latest branch. Did you do anything to it? Seems like it's causing main thread death during object serialisation and I recall you were looking into tinkering with that

**Comment by HarvelsX** [comment] 2022-01-13 12:39
It's pretty weird, but this is the first thread dump after which the others came, and eventually the server stopped responding and kept throwing `java.lang.OutOfMemoryError: Java heap space`
I don't think it's about my changes, they just replace the caching method with Guava Cache.

**Comment by HarvelsX** [comment] 2022-01-13 12:45
Looking at the code, I think the serialization of statistics looks creepy, lots of `HashMap` that are later serialized by `ObjectOutputStream`, which is not productive as it is.

**Comment by HarvelsX** [comment] 2022-01-13 13:14
Probably over time, because of the internal `ObjectOutputStream` cache or for some other reason, serialization processing slows down, which causes delays. I try to analyze memory dump and timings from Spark.

https://timings.aikar.co/?id=c1f791632afe40908f0d2e4292c103cd#timings
![Timings](https://user-images.githubusercontent.com/90945793/149336679-308663b0-c1f9-4836-b62d-4ff025e841fa.png)

**Comment by WiIIiam278** [comment] 2022-01-13 13:17
Statistic data is a bit of a pain to serialise because they can be per block/entity etc but I don't believe that data is getting serialized twice. The way it's done is that it takes the players stat values and puts them in a serializable object object which is then cached and put on SQL. If you can reproduce this on the main branch then we can have a look but I think it might be worth filing this on your branch and investigation first. I don't think it's the ObjectInputStream causing a memory leak and as mentioned I think I would have received reports of this if it were happening on the main branch

**Comment by HarvelsX** [comment] 2022-01-13 13:32
Okay, let's see if that changes.

**Comment by WiIIiam278** [comment] 2022-01-15 14:49
I'm going to close this for now just because it's not been replicated on the current branch so isn't a valid issue on this fork

**Closed by WiIIiam278** 2022-01-15 14:49 UTC
Labels: status: needs testing
