### ISSUE TITLE
Add support for Slimefun items (via dough CustomItemStack API)

### ISSUE THREAD

**Issue by DJelly4K** [WiIIiam278/HuskSync#13] opened 2021-12-25 22:09 UTC
When using Slimefun and HuskSync on the subserver, the guide book that comes with Slimefun cannot be opened
This problem also occurs on ItemJoin, and the menu bound with the menu command cannot be opened.
If you don’t call the chest inventory like ChestCommands, the item can be used normally
After the cross-server has not been tested

Proxy: [FlameCord](https://github.com/2lstudios-mc/FlameCord) 0.6.8
Backend servers: [Patina](https://github.com/PatinaMC/Patina/) 1.17.1 (a paper fork)
MariaDB 10.5.6 | Data is stored in UTF-8 format
Redis 6.2.6
all working normally
HuskSync: 1.2.2

**Comment by WiIIiam278** [comment] 2021-12-25 23:54
Can you confirm if this happens on first join, or if the book only stops working after relief

**Comment by DJelly4K** [comment] 2021-12-26 05:13
> Can you confirm if this happens on first join, or if the book only stops working after relog?

after relog

**Comment by WiIIiam278** [comment] 2021-12-26 12:25
Unfortunately this is down to Slimefun using (dough)[https://github.com/baked-libs/dough]'s custom ItemStack API which doesn't make use of persistent data containers; it's not supported by this plugin. 
Therefore, not a bug, as per [README](https://github.com/WiIIiam278/HuskSync#are-modded-items-supported). I'll convert this issue to a feature request to support Slimefun.

**Comment by zimzaza4** [comment] 2022-04-13 22:45
ummm but slimefun still use pdc and i successfully sync the slimefun items

**Comment by WiIIiam278** [comment] 2022-04-14 12:52
> ummm but slimefun still use PDC and i successfully sync the slimefun items

Oh, OK- guess I misinterpreted. In that case, I'll close this.

**Closed by WiIIiam278** 2022-04-14 12:52 UTC
Labels: type: feature request
