### ISSUE TITLE
Maps not displaying in item frames

### ISSUE THREAD

**Issue by RillSoji** [WiIIiam278/HuskSync#277] opened 2024-04-11 03:10 UTC
HuskSync v 3.4
DB Type: MariaDB
Velocity 3.3.0 SNAPSHOT 369
PaperMC 1.20.4 #466

Maps transfer just fine from server to server but appear as blank in item frames after a player relogs or changes servers unless they have the map currently in their inventory. Players must pick up and replace the map to be able to see it again.

**Comment by ProdPreva1l** [comment] 2024-04-11 03:16
Interesting, that must be something to do with how maps generate on item frames.

**Comment by WiIIiam278** [comment] 2024-04-11 14:10
Just tried reproducing and simply wasn't able to :(
Did you delete your `maps` folder inside `/plugins/HuskSync`? Or perhaps accidentally turn off map syncing? Or when you check console are their errors writing files to that directory?

**Comment by WiIIiam278** [comment] 2024-04-18 01:16
Closing as unable to reproduce. Do get in touch on discord though so we can look into this again in more detail together if it still persists :)

**Closed** 2024-04-18 01:15 UTC
Labels: status: needs testing
