### ISSUE TITLE
Using MMOItems which change the player's health attribute base value causes an IllegalArgumentException

### ISSUE THREAD

**Issue by justaureus** [WiIIiam278/HuskSync#5] opened 2021-11-20 06:11 UTC
When using an MMOItem that changes the user's health, it can cause an IllegalArgumentException.  This may be incorrect, but I believe it may have to do with how MMOItems sets the health.  It does not seem to set the health based on the MAX_HEALTH attribute (which would be a value between 0.0 and 1.0) but rather sets it directly (as seen below being 235.0).  

Here is an example:
```[13:36:29 WARN]: [HuskSync] Task #66723 for HuskSync v1.0.3 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 1.0, but was 235.0. (attribute base value: 235.0, player: Alzter_)
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:127) ~[patched_1.16.5.jar:git-Paper-788]
        at me.william278.husksync.bukkit.util.PlayerSetter.lambda$setPlayerFrom$0(PlayerSetter.java:152) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by WiIIiam278** [comment] 2021-11-20 09:25
Duplicate of #2

**Closed by WiIIiam278** 2021-11-20 09:25 UTC
Labels: type: bug
