### ISSUE TITLE
Item on hand and offhand occasionally drop on server switch / disconnect

### ISSUE THREAD

**Issue by nhanledev** [WiIIiam278/HuskSync#232] opened 2024-01-22 18:14 UTC
Item on player main hand and offhand sometime (rarely) disappear after switching server.

It drops at the last location of the player on the previous server.

I still can not reproduce it on the development server, but I've seen the problem on production server.

What do you think?

**Comment by WiIIiam278** [comment] 2024-01-23 01:35
Could you provide a video demonstrating this behaviour? Also, attach any plugins you have installed on production. This shouldn't happen typically; the only behaviour in which HuskSync will drop something to the floor is an item on the player's cursor in their inventory

**Comment by WiIIiam278** [comment] 2024-02-01 13:04
Closing as unable to reproduce

**Closed by WiIIiam278** 2024-02-01 13:04 UTC
Labels: status: needs testing
